### ISSUE TITLE
کانفیگ ایجاد نمی شود

### ISSUE THREAD

**Issue by prxpostern** [Ptechgithub/xray-fragment#1]
کد کانفیگ را میدهد ولی فایلش ساخته نمیشود. کد uuid هم داخل کانفیگی که میسازد وجود ندارد.

**Comment by Ptechgithub** [comment]
توی اتصال به termux مشکل دارید اگه چیز مهمی داخلش ندارید .دستور
rm -rf $PREFIX 
بزنید تا TERMUX ریست بشه و کلیر دیتا کنید و از اول نصب کنید.
